import type { Metadata } from "next";
import "./globals.css";
import ClerkProviderWrapper from "../components2/ClerkProviderWrapper";
import { Toaster } from "@/src/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProviderWrapper>
      <html lang="en">
        <body className="antialiased">
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProviderWrapper>
  );
}
